CREATE TABLE t_booksite_activitytype (
	PK_ACTIVITYTYPE_ID VARCHAR(32) NOT NULL,
	activityType_NAME VARCHAR(255),
	activityType_sort INT,
	FK_SITESTATUS_NO VARCHAR(32),
	PRIMARY KEY (PK_ACTIVITYTYPE_ID)
);

CREATE TABLE t_booksite_sitestatus (
	pk_SITESTATUS_ID VARCHAR(32) NOT NULL,
	SITESTATUS_NAME VARCHAR(255),
	siteStatus_checkId INT,
	PRIMARY KEY (pk_SITESTATUS_ID)
);

CREATE TABLE t_booksite_booksite (
	pk_BOOKSITE_ID VARCHAR(32) NOT NULL,
	bookSite_beginTime DATETIME,
	bookSite_endTime DATETIME,
	bookSite_explain VARCHAR(255),
	bookSite_uploadDateTime DATETIME,
	bookSite_people VARCHAR(255),
	bookSite_statusId INT,
	FK_SITE_NO VARCHAR(32),
	FK_ACTIVITYLEVEL_NO VARCHAR(32),
	FK_ACTIVITYTYPE_NO VARCHAR(32),
	FK_USER_NO VARCHAR(32),
	bookSite_clashId TEXT,
	PRIMARY KEY (pk_BOOKSITE_ID)
);

CREATE TABLE t_booksite_site_type (
	TYPE_NO VARCHAR(32) NOT NULL,
	SITE_NO VARCHAR(32) NOT NULL,
	PK_T_BOOKSITE_SITE_TYPE_ID VARCHAR(32) NOT NULL,
	PRIMARY KEY (PK_T_BOOKSITE_SITE_TYPE_ID)
);

CREATE TABLE t_booksite_site (
	PK_SITE_ID VARCHAR(32) NOT NULL,
	SITE_NAME VARCHAR(255),
	SITE_PICNAME VARCHAR(255),
	SITE_EDITORPICNAME VARCHAR(255),
	site_area VARCHAR(255),
	site_capacity VARCHAR(255),
	site_address VARCHAR(255),
	site_other VARCHAR(255),
	FK_SITESTATUS_NO VARCHAR(32),
	PRIMARY KEY (PK_SITE_ID)
);

CREATE TABLE t_booksite_activitylevel (
	PK_activityLevel_ID VARCHAR(32) NOT NULL,
	activityLevel_NAME VARCHAR(255),
	activityLevel_sort INT,
	FK_SITESTATUS_NO VARCHAR(32),
	PRIMARY KEY (PK_activityLevel_ID)
);

CREATE TABLE t_booksite_site_level (
	LEVEL_NO VARCHAR(32) NOT NULL,
	SITE_NO VARCHAR(32) NOT NULL,
	PK_T_BOOKSITE_SITE_LEVEL_ID VARCHAR(32) NOT NULL,
	PRIMARY KEY (PK_T_BOOKSITE_SITE_LEVEL_ID)
);

CREATE INDEX FKA118943434EC098D ON t_booksite_booksite (FK_ACTIVITYTYPE_NO ASC);

CREATE INDEX FK5B28A1F02D463B27 ON t_booksite_site_level (SITE_NO ASC);

CREATE INDEX FK5B28A1F03FC6DBCA ON t_booksite_site_level (LEVEL_NO ASC);

CREATE INDEX FKEA2E872E2D463B27 ON t_booksite_site_type (SITE_NO ASC);

CREATE INDEX FK50EC8F4D80767ACD ON t_booksite_activitytype (FK_SITESTATUS_NO ASC);

CREATE INDEX FKA118943411582813 ON t_booksite_booksite (FK_ACTIVITYLEVEL_NO ASC);

CREATE INDEX FKA1189434F34706DD ON t_booksite_booksite (FK_USER_NO ASC);

CREATE INDEX FKCC2B9DB180767ACD ON t_booksite_activitylevel (FK_SITESTATUS_NO ASC);

CREATE INDEX FKA11894347B359AD ON t_booksite_booksite (FK_SITE_NO ASC);

CREATE INDEX FKEA2E872EBA8C82F6 ON t_booksite_site_type (TYPE_NO ASC);

CREATE INDEX FK370EDFCB80767ACD ON t_booksite_site (FK_SITESTATUS_NO ASC);

